version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - misspell
    - noctx
    - revive
    - sqlclosecheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
