package model

import "testing"

func TestNewID(t *testing.T) {
	id := NewID()
	if id == "" {
		t.Fatal("NewID returned empty string")
	}
	if !IsValidID(id) {
		t.Fatalf("NewID returned invalid UUID: %s", id)
	}

	id2 := NewID()
	if id == id2 {
		t.Fatal("two calls to NewID returned the same value")
	}
}

func TestIsValidID_Valid(t *testing.T) {
	// Standard UUID format
	if !IsValidID("550e8400-e29b-41d4-a716-446655440000") {
		t.Fatal("expected valid UUID to pass")
	}
	// UUIDv7 generated by NewID
	if !IsValidID(NewID()) {
		t.Fatal("expected NewID() result to be valid")
	}
}

func TestIsValidID_Invalid(t *testing.T) {
	cases := []struct {
		name  string
		input string
	}{
		{"empty", ""},
		{"not a uuid", "not-a-uuid"},
		{"partial uuid", "550e8400-e29b-41d4-a716"},
		{"too short", "abc"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if IsValidID(tc.input) {
				t.Fatalf("expected %q to be invalid", tc.input)
			}
		})
	}
}
